version = 1
SPDX-PackageName = "ui5-typescript"
SPDX-PackageSupplier = "SAP OpenUI5 <openui5@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/UI5/typescript"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and UI5-TypeScript contributors"
SPDX-License-Identifier = "Apache-2.0"
